### Variables
@baseUrl = http://localhost:3000
@contentType = application/json


# health check
GET {{baseUrl}}



### Restaurant listing api
GET {{baseUrl}}/api/restaurants/list

### Restaurant by id
GET {{baseUrl}}/api/restaurants/6a2ab2675e8f92e9f4bd31f4
### Dish add api
POST {{baseUrl}}/api/dishes/add
Content-Type: {{contentType}}

{
  "restaurantId": "6a2ab2675e8f92e9f4bd31f4",
  "name": "Chicken fry",
  "description": "Roles with fresh cabbage, carrots, and glass noodles. Served with sweet chili sauce.",
  "isActive": true,
  "tags": ["nonveg", "appetizer", "crispy", "asian"],
  "serving": [
    {
      "title": "9 Pieces",
      "value": 2,
      "price": 210,
      "currency": "INR"
    }
  ]
}

### Dish listing api
GET {{baseUrl}}/api/dishes/list?page=1&limit=10

### Dish listing with search
GET {{baseUrl}}/api/dishes/list?page=1&limit=10&search=chicken