export const restaurantDescriptions: string[] = [
  "Cozy spot serving authentic local cuisine with a modern twist.",
  "Family-friendly restaurant known for generous portions and warm service.",
  "Upscale dining experience with a focus on seasonal ingredients.",
  "Quick-service eatery perfect for casual meals and takeout.",
  "Hidden gem offering rich flavors and traditional recipes.",
  "Vibrant atmosphere with a diverse international menu.",
  "Minimalist cafe specializing in fresh, healthy dishes.",
  "Classic diner serving comfort food favorites all day.",
  "Trendy restaurant popular for fusion cuisine and creative plating.",
  "Relaxed dining space with a focus on grilled specialties.",
  "Neighborhood favorite known for consistency and quality.",
  "Elegant venue ideal for date nights and special occasions.",
  "Street-style food experience with bold and spicy flavors.",
  "Vegetarian-friendly menu with innovative plant-based dishes.",
  "Seafood-focused restaurant with fresh daily catches.",
  "Compact but lively space with fast and friendly service.",
  "Artisanal kitchen offering handcrafted meals and desserts.",
  "Casual hangout spot with a mix of local and global dishes.",
  "Rustic ambiance paired with hearty, home-style cooking.",
  "Modern bistro delivering a balance of taste and presentation.",
];
